
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.20.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace cs {
    using Terminal.Gui;
    
    
    public partial class lol {
        
        public lol() {
            InitializeComponent();
        }
    }
}
