
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.20.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace BBS.Page {
    using System;
    using Terminal.Gui;
    
    
    public partial class Login : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme whiteOnBlack;
        
        private Terminal.Gui.Label loginLabel;
        
        private Terminal.Gui.TextField passwdField;
        
        private Terminal.Gui.Label passwdLabel;
        
        private Terminal.Gui.TextField loginField;
        
        private Terminal.Gui.Button loginButton;
        
        private Terminal.Gui.Button signUpButton;
        
        private void InitializeComponent() {
            this.signUpButton = new Terminal.Gui.Button();
            this.loginButton = new Terminal.Gui.Button();
            this.loginField = new Terminal.Gui.TextField();
            this.passwdLabel = new Terminal.Gui.Label();
            this.passwdField = new Terminal.Gui.TextField();
            this.loginLabel = new Terminal.Gui.Label();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.whiteOnBlack = new Terminal.Gui.ColorScheme();
            this.whiteOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.whiteOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.whiteOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Magenta);
            this.whiteOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Magenta);
            this.whiteOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.ColorScheme = this.greyOnBlack;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.loginLabel.Width = 4;
            this.loginLabel.Height = 1;
            this.loginLabel.X = 45;
            this.loginLabel.Y = 10;
            this.loginLabel.ColorScheme = this.whiteOnBlack;
            this.loginLabel.Data = "loginLabel";
            this.loginLabel.Text = "login";
            this.loginLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.loginLabel);
            this.passwdField.Width = 20;
            this.passwdField.Height = 1;
            this.passwdField.X = 51;
            this.passwdField.Y = 10;
            this.passwdField.Secret = false;
            this.passwdField.Data = "passwdField";
            this.passwdField.Text = "";
            this.passwdField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.passwdField);
            this.passwdLabel.Width = 8;
            this.passwdLabel.Height = 1;
            this.passwdLabel.X = 42;
            this.passwdLabel.Y = 12;
            this.passwdLabel.ColorScheme = this.whiteOnBlack;
            this.passwdLabel.Data = "passwdLabel";
            this.passwdLabel.Text = "password";
            this.passwdLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.passwdLabel);
            this.loginField.Width = 20;
            this.loginField.Height = 1;
            this.loginField.X = 51;
            this.loginField.Y = 12;
            this.loginField.Secret = false;
            this.loginField.Data = "loginField";
            this.loginField.Text = "";
            this.loginField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.loginField);
            this.loginButton.Width = 9;
            this.loginButton.Height = 1;
            this.loginButton.X = 51;
            this.loginButton.Y = 16;
            this.loginButton.ColorScheme = this.whiteOnBlack;
            this.loginButton.Data = "loginButton";
            this.loginButton.Text = "Login";
            this.loginButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.loginButton.IsDefault = false;
            this.Add(this.loginButton);
            this.signUpButton.Width = 11;
            this.signUpButton.Height = 1;
            this.signUpButton.X = 51;
            this.signUpButton.Y = 18;
            this.signUpButton.ColorScheme = this.whiteOnBlack;
            this.signUpButton.Data = "signUpButton";
            this.signUpButton.Text = "Sign Up";
            this.signUpButton.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.signUpButton.IsDefault = false;
            this.Add(this.signUpButton);
        }
    }
}
