CREATE DATABASE beta3;
USE beta3;

CREATE TABLE User (
	ID 				INTEGER PRIMARY KEY AUTO_INCREMENT,
    Username 		VARCHAR(32) UNIQUE NOT NULL,
    PasswordHash 	VARCHAR(256) NOT NULL,
    Joined 			DATETIME NOT NULL
);

CREATE TABLE Message (
	ID 				INTEGER PRIMARY KEY AUTO_INCREMENT,
    SenderID 		INTEGER NOT NULL,
    ReceiverID 	INTEGER NOT NULL,
    Content 		TEXT NOT NULL,
    Sent 			DATETIME NOT NULL,
    
    FOREIGN KEY (SenderID) REFERENCES User(ID),
    FOREIGN KEY (ReceiverID) REFERENCES User(ID)
);

CREATE TABLE Ban (
	ID 				INTEGER PRIMARY KEY AUTO_INCREMENT,
    UserID 		INTEGER NOT NULL,
    Reason 			VARCHAR(256) NULL,
    Start 			DATETIME NOT NULL,
    End 			DATETIME NULL,
    
    FOREIGN KEY (UserID) REFERENCES User(ID)
);

CREATE TABLE Board (
	ID				INTEGER PRIMARY KEY AUTO_INCREMENT,
    Name			VARCHAR(64) NOT NULL,
);

CREATE TABLE Moderator (
	ID				INTEGER PRIMARY KEY AUTO_INCREMENT,
    UserID			INTEGER NOT NULL,
    BoardID		INTEGER NOT NULL,
    
    FOREIGN KEY (UserID) REFERENCES User(ID),
    FOREIGN KEY (BoardID) REFERENCES Board(ID)
);

CREATE TABLE Thread (
	ID				INTEGER PRIMARY KEY AUTO_INCREMENT,
    BoardID		INTEGER NOT NULL,
    Title			VARCHAR(256) NOT NULL,
    
    FOREIGN KEY (BoardID) REFERENCES Board(ID)
);

CREATE TABLE Post (
	ID				INTEGER PRIMARY KEY AUTO_INCREMENT,
    UserID			INTEGER NOT NULL,
    ThreadID		INTEGER NOT NULL,
    Content			TEXT NOT NULL,
    Created			DATETIME NOT NULL,
    
    FOREIGN KEY (UserID) REFERENCES User(ID),
    FOREIGN KEY (ThreadID) REFERENCES Thread(ID)
);

CREATE TABLE Bookmark (
	ID				INTEGER PRIMARY KEY AUTO_INCREMENT,
    BoardID		INTEGER NULL,
    ThreadID		INTEGER NULL,
	UserID			INTEGER NOT NULL,
    
    FOREIGN KEY (BoardID) REFERENCES Board(ID),
    FOREIGN KEY (ThreadID) REFERENCES Thread(ID),
    FOREIGN KEY (UserID) REFERENCES User(ID)
);
