CREATE DATABASE BBS;
USE BBS;

CREATE TABLE User (
	ID 				INTEGER PRIMARY KEY AUTO_INCREMENT,
    Username 		VARCHAR(32) UNIQUE NOT NULL,
    PasswordHash 	VARCHAR(256) NOT NULL,
    Joined 			DATETIME NOT NULL
);

CREATE TABLE Message (
	ID 				INTEGER PRIMARY KEY AUTO_INCREMENT,
    Sender_ID 		INTEGER NOT NULL,
    Receiver_ID 	INTEGER NOT NULL,
    Content 		TEXT NOT NULL,
    Sent 			DATETIME NOT NULL,
    
    FOREIGN KEY (Sender_ID) REFERENCES User(ID),
    FOREIGN KEY (Receiver_ID) REFERENCES User(ID)
);

CREATE TABLE Ban (
	ID 				INTEGER PRIMARY KEY AUTO_INCREMENT,
    User_ID 		INTEGER NOT NULL,
    Reason 			VARCHAR(256) NULL,
    Start 			DATETIME NOT NULL,
    End 			DATETIME NULL,
    
    FOREIGN KEY (User_ID) REFERENCES User(ID)
);

CREATE TABLE Board (
	ID				INTEGER PRIMARY KEY AUTO_INCREMENT,
    Name			VARCHAR(64) NOT NULL,
    Description		VARCHAR(256) NOT NULL
);

CREATE TABLE Moderator (
	ID				INTEGER PRIMARY KEY AUTO_INCREMENT,
    User_ID			INTEGER NOT NULL,
    Board_ID		INTEGER NOT NULL,
    
    FOREIGN KEY (User_ID) REFERENCES User(ID),
    FOREIGN KEY (Board_ID) REFERENCES Board(ID)
);

CREATE TABLE Thread (
	ID				INTEGER PRIMARY KEY AUTO_INCREMENT,
    Board_ID		INTEGER NOT NULL,
    Title			VARCHAR(256) NOT NULL,
    
    FOREIGN KEY (Board_ID) REFERENCES Board(ID)
);

CREATE TABLE Post (
	ID				INTEGER PRIMARY KEY AUTO_INCREMENT,
    User_ID			INTEGER NOT NULL,
    Thread_ID		INTEGER NOT NULL,
    Content			TEXT NOT NULL,
    Created			DATETIME NOT NULL,
    
    FOREIGN KEY (User_ID) REFERENCES User(ID),
    FOREIGN KEY (Thread_ID) REFERENCES Thread(ID)
);

CREATE TABLE Bookmark (
	ID				INTEGER PRIMARY KEY AUTO_INCREMENT,
    Board_ID		INTEGER NULL,
    Thread_ID		INTEGER NULL,
	User_ID			INTEGER NOT NULL,
    
    FOREIGN KEY (Board_ID) REFERENCES Board(ID),
    FOREIGN KEY (Thread_ID) REFERENCES Thread(ID),
    FOREIGN KEY (User_ID) REFERENCES User(ID)
);
